// Generates map/sw.js with a fully-enumerated cache list (fonts, sprites,
// vendor bundle, baked data, style, the .pmtiles) so nothing is missed and
// nothing needs hand-maintaining as those directories change. Re-run this
// (via `make map`) whenever any vendored/baked file changes — CACHE bumps
// every run so old caches get evicted and the new assets actually take over.
import fs from "node:fs";
import path from "node:path";

const MAP_DIR = new URL("../map/", import.meta.url);
const mapPath = (p) => path.join(new URL(MAP_DIR).pathname, p);

function listRel(dir) {
  const abs = mapPath(dir);
  if (!fs.existsSync(abs)) return [];
  return fs.readdirSync(abs, { recursive: true })
    .filter((f) => fs.statSync(path.join(abs, f)).isFile())
    .map((f) => `./${dir}/${f}`);
}

const assets = [
  "./map.html",
  "./manifest.webmanifest",
  "./style.json",
  "./tokyo.pmtiles",
  "./icon-192.png",
  "./icon-512.png",
  ...listRel("vendor"),
  ...listRel("fonts"),
  ...listRel("sprites"),
  ...listRel("data"),
];

const CACHE = `japan-map-${new Date().toISOString().slice(0, 10)}`;

const sw = `// Generated by scripts/build_sw.mjs — do not hand-edit, re-run the build.
const CACHE = ${JSON.stringify(CACHE)};
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener("install", (e) =>
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting())));

self.addEventListener("activate", (e) =>
  e.waitUntil(caches.keys().then((ks) =>
    Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())));

// map.html fetches tokyo.pmtiles as one plain GET (see its BufferSource
// note — GitHub Pages doesn't reliably honor Range requests on this file),
// so a plain cache-first-then-network handler is all this needs; there's no
// Range request to proxy.
self.addEventListener("fetch", (e) => {
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((r) => r || fetch(e.request)));
});
`;

fs.writeFileSync(mapPath("sw.js"), sw);
console.log(`wrote map/sw.js (cache ${CACHE}, ${assets.length} precached assets)`);
