// Generates map/sw.js with a fully-enumerated cache list (fonts, sprites,
// vendor bundle, baked data, style, the .pmtiles) so nothing is missed and
// nothing needs hand-maintaining as those directories change. Re-run this
// (via `make map`) whenever any vendored/baked file changes — CACHE bumps
// every run so old caches get evicted and the new assets actually take over.
import fs from "node:fs";
import path from "node:path";

const MAP_DIR = new URL("../map/", import.meta.url);
const mapPath = (p) => path.join(new URL(MAP_DIR).pathname, p);

function listRel(dir) {
  const abs = mapPath(dir);
  if (!fs.existsSync(abs)) return [];
  return fs.readdirSync(abs, { recursive: true })
    .filter((f) => fs.statSync(path.join(abs, f)).isFile())
    .map((f) => `./${dir}/${f}`);
}

const assets = [
  "./map.html",
  "./manifest.webmanifest",
  "./style.json",
  "./tokyo.pmtiles",
  "./icon-192.png",
  "./icon-512.png",
  ...listRel("vendor"),
  ...listRel("fonts"),
  ...listRel("sprites"),
  ...listRel("data"),
];

const CACHE = `japan-map-${new Date().toISOString().slice(0, 10)}`;

const sw = `// Generated by scripts/build_sw.mjs — do not hand-edit, re-run the build.
const CACHE = ${JSON.stringify(CACHE)};
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener("install", (e) =>
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting())));

self.addEventListener("activate", (e) =>
  e.waitUntil(caches.keys().then((ks) =>
    Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())));

// The .pmtiles file is fetched by MapLibre/pmtiles.js via HTTP Range
// requests. A cached Response can't be range-sliced directly, so on the
// first range request we pull the whole cached (or freshly fetched) file
// into memory once and serve every subsequent range from that buffer.
let pmBufPromise = null;
async function pmBuffer(url) {
  if (!pmBufPromise) {
    pmBufPromise = (async () => {
      const c = await caches.open(CACHE);
      const res = (await c.match(url, { ignoreSearch: true })) || (await fetch(url));
      return res.arrayBuffer();
    })();
  }
  return pmBufPromise;
}

self.addEventListener("fetch", (e) => {
  const req = e.request;
  const range = req.headers.get("range");
  if (range && req.url.endsWith(".pmtiles")) {
    e.respondWith((async () => {
      const buf = await pmBuffer(req.url);
      const m = /bytes=(\\d+)-(\\d*)/.exec(range);
      const start = Number(m[1]);
      const end = m[2] ? Number(m[2]) : buf.byteLength - 1;
      const slice = buf.slice(start, end + 1);
      return new Response(slice, {
        status: 206,
        headers: {
          "Content-Range": \`bytes \${start}-\${end}/\${buf.byteLength}\`,
          "Accept-Ranges": "bytes",
          "Content-Length": String(slice.byteLength),
          "Content-Type": "application/octet-stream",
        },
      });
    })());
    return;
  }
  e.respondWith(caches.match(req, { ignoreSearch: true }).then((r) => r || fetch(req)));
});
`;

fs.writeFileSync(mapPath("sw.js"), sw);
console.log(`wrote map/sw.js (cache ${CACHE}, ${assets.length} precached assets)`);
