// Generates a service worker for each offline mini-PWA (map/sw.js,
// recorder/sw.js) with a fully-enumerated cache list so nothing is missed
// as those directories change. Re-run this (via `make map`) whenever any
// vendored/baked file in either directory changes.
//
// CACHE is a hash of every precached file's actual bytes, not a date —
// a date only bumps once per calendar day, so two rebuilds on the same day
// (e.g. re-baking a data layer after a correction) would leave a stale
// cache installed and silently serving the old content indefinitely, since
// the browser only re-runs a service worker's install step when the
// worker's own script byte-differs from what's currently registered.
// Content-hashing means ANY asset change changes this file's bytes too.
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const ROOT = new URL("../", import.meta.url);
const rootPath = (p) => path.join(new URL(ROOT).pathname, p);

function listRel(dir, sub) {
  const abs = rootPath(path.join(dir, sub));
  if (!fs.existsSync(abs)) return [];
  return fs.readdirSync(abs, { recursive: true })
    .filter((f) => fs.statSync(path.join(abs, f)).isFile())
    .map((f) => `./${sub}/${f}`);
}

const TARGETS = {
  map: [
    "./map.html",
    "./basemap.mjs",
    "./manifest.webmanifest",
    "./style.json",
    "./tokyo.pmtiles",
    "./icon-192.png",
    "./icon-512.png",
    ...listRel("map", "vendor"),
    ...listRel("map", "fonts"),
    ...listRel("map", "sprites"),
    ...listRel("map", "data"),
  ],
  recorder: [
    "./recorder.html",
    "./manifest.webmanifest",
    "./icon-192.png",
    "./icon-512.png",
    ...listRel("recorder", "vendor"),
    ...listRel("recorder", "data"),
  ],
};

for (const [dir, assets] of Object.entries(TARGETS)) {
  const hash = crypto.createHash("sha1");
  for (const asset of assets) hash.update(fs.readFileSync(rootPath(path.join(dir, asset))));
  const CACHE = `japan-${dir}-${hash.digest("hex").slice(0, 12)}`;

  const sw = `// Generated by scripts/build_sw.mjs — do not hand-edit, re-run the build.
const CACHE = ${JSON.stringify(CACHE)};
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener("install", (e) =>
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting())));

self.addEventListener("activate", (e) =>
  e.waitUntil(caches.keys().then((ks) =>
    Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())));

self.addEventListener("fetch", (e) => {
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((r) => r || fetch(e.request)));
});
`;

  fs.writeFileSync(rootPath(path.join(dir, "sw.js")), sw);
  console.log(`wrote ${dir}/sw.js (cache ${CACHE}, ${assets.length} precached assets)`);
}
