// Generated by scripts/build_sw.mjs — do not hand-edit, re-run the build.
const CACHE = "japan-map-2026-09-18";
const ASSETS = [
  "./map.html",
  "./manifest.webmanifest",
  "./style.json",
  "./tokyo.pmtiles",
  "./icon-192.png",
  "./icon-512.png",
  "./vendor/maplibre-gl-shared.mjs",
  "./vendor/maplibre-gl-worker.mjs",
  "./vendor/maplibre-gl.css",
  "./vendor/maplibre-gl.mjs",
  "./vendor/pmtiles.js",
  "./fonts/Noto Sans Regular/0-255.pbf",
  "./fonts/Noto Sans Regular/1024-1279.pbf",
  "./fonts/Noto Sans Regular/11264-11519.pbf",
  "./fonts/Noto Sans Regular/11520-11775.pbf",
  "./fonts/Noto Sans Regular/1280-1535.pbf",
  "./fonts/Noto Sans Regular/1536-1791.pbf",
  "./fonts/Noto Sans Regular/1792-2047.pbf",
  "./fonts/Noto Sans Regular/2048-2303.pbf",
  "./fonts/Noto Sans Regular/2304-2559.pbf",
  "./fonts/Noto Sans Regular/256-511.pbf",
  "./fonts/Noto Sans Regular/2560-2815.pbf",
  "./fonts/Noto Sans Regular/2816-3071.pbf",
  "./fonts/Noto Sans Regular/3072-3327.pbf",
  "./fonts/Noto Sans Regular/3328-3583.pbf",
  "./fonts/Noto Sans Regular/3584-3839.pbf",
  "./fonts/Noto Sans Regular/3840-4095.pbf",
  "./fonts/Noto Sans Regular/4096-4351.pbf",
  "./fonts/Noto Sans Regular/41984-42239.pbf",
  "./fonts/Noto Sans Regular/42240-42495.pbf",
  "./fonts/Noto Sans Regular/42496-42751.pbf",
  "./fonts/Noto Sans Regular/42752-43007.pbf",
  "./fonts/Noto Sans Regular/43008-43263.pbf",
  "./fonts/Noto Sans Regular/43264-43519.pbf",
  "./fonts/Noto Sans Regular/4352-4607.pbf",
  "./fonts/Noto Sans Regular/43520-43775.pbf",
  "./fonts/Noto Sans Regular/43776-44031.pbf",
  "./fonts/Noto Sans Regular/4608-4863.pbf",
  "./fonts/Noto Sans Regular/4864-5119.pbf",
  "./fonts/Noto Sans Regular/512-767.pbf",
  "./fonts/Noto Sans Regular/5888-6143.pbf",
  "./fonts/Noto Sans Regular/6144-6399.pbf",
  "./fonts/Noto Sans Regular/6400-6655.pbf",
  "./fonts/Noto Sans Regular/64256-64511.pbf",
  "./fonts/Noto Sans Regular/65024-65279.pbf",
  "./fonts/Noto Sans Regular/6656-6911.pbf",
  "./fonts/Noto Sans Regular/6912-7167.pbf",
  "./fonts/Noto Sans Regular/7168-7423.pbf",
  "./fonts/Noto Sans Regular/7424-7679.pbf",
  "./fonts/Noto Sans Regular/768-1023.pbf",
  "./fonts/Noto Sans Regular/7680-7935.pbf",
  "./fonts/Noto Sans Regular/7936-8191.pbf",
  "./fonts/Noto Sans Regular/8192-8447.pbf",
  "./fonts/Noto Sans Regular/8448-8703.pbf",
  "./fonts/Noto Sans Regular/8704-8959.pbf",
  "./fonts/Noto Sans Regular/9216-9471.pbf",
  "./fonts/Noto Sans Regular/9472-9727.pbf",
  "./fonts/Noto Sans Regular/9728-9983.pbf",
  "./sprites/light.json",
  "./sprites/light.png",
  "./sprites/light@2x.json",
  "./sprites/light@2x.png",
  "./data/japaneat.geojson",
  "./data/pois.geojson",
  "./data/pois.json",
  "./data/trip.locations.json",
  "./data/vk_spots.geojson"
];

self.addEventListener("install", (e) =>
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting())));

self.addEventListener("activate", (e) =>
  e.waitUntil(caches.keys().then((ks) =>
    Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())));

// map.html fetches tokyo.pmtiles as one plain GET (see its BufferSource
// note — GitHub Pages doesn't reliably honor Range requests on this file),
// so a plain cache-first-then-network handler is all this needs; there's no
// Range request to proxy.
self.addEventListener("fetch", (e) => {
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((r) => r || fetch(e.request)));
});
